name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start JSON Server
        run: yarn init:db &
        env:
          PORT: 3000

      - name: Start Vite Development Server
        run: yarn dev --port 3001 &
        env:
          PORT: 3001

      - name: Wait for servers to start
        run: |
          echo "Waiting for servers to start..."
          sleep 10

      - name: Run Playwright Tests
        run: yarn playwright test
